export enum BusinessPlanStatus {
  INACTIVE = 0,
  ACTIVE = 1,
  PENDING = 2,
  APPROVED = 3,
  REJECTED = 4,
  REQUESTAPPROVE = 5
}

export const defaultBusinessPlan = {
  id: 0,
  createdAt: '',
  lastUpdatedAt: '',
  createdBy: 0,
  lastUpdatedBy: 0,
  lastProgramUpdate: '',
  code: '',
  status: 0,
  lastUpdatedProgram: '',
  draftPoId: 0,
  contractId: 0,
  codeBooking: 0,
  totalQuantity: 0,
  expectedPrice: 0,
  currency: '',
  isApprove: 0,
  totalRevenueExcludingVat: 0,
  breakEvenPrice: 0,
  actualBusinessProfit: 0,
  profitMarginPercentage: 0,
  contractCode: '',
  businessPlanCostItem: {
    id: 0,
    createdAt: '',
    lastUpdatedAt: '',
    createdBy: 0,
    lastUpdatedBy: 0,
    lastProgramUpdate: '',
    code: '',
    status: 0,
    lastUpdatedProgram: '',
    businessPlanId: 0,
    totalFreightEbs: 0,
    factoryToPortCost: 0,
    warehouseRentalCost: 0,
    truckingCost: 0,
    localCharges: 0,
    earlyUnloadingFee: 0,
    thcFee: 0,
    sealFee: 0,
    infrastructureFee: 0,
    customsSupervisionFee: 0,
    fumigationPerContainer: 0,
    fumigationPerLot: 0,
    quarantineFee: 0,
    ttFee: 0,
    coFee: 0,
    doFee: 0,
    palletFee: 0,
    jumboBagFee: 0,
    amsFee: 0,
    customsTeamFee: 0,
    customsReceptionFee: 0,
    clearanceCost: 0,
    interestCost: 0,
    vatInterestCost: 0,
    exchangeRateCost: 0,
    dhlFee: 0,
    brokerageFee: 0,
    taxRefundCost: 0,
    qcCost: 0,
    generalManagementCost: 0,
    currency: ''
  },
  businessPlanSupplierItems: [],
  businessPlanTransactionInfoItem: {
    id: 0,
    createdAt: '',
    lastUpdatedAt: '',
    createdBy: 0,
    lastUpdatedBy: 0,
    lastProgramUpdate: '',
    code: '',
    status: 0,
    lastUpdatedProgram: '',
    businessPlanId: 0,
    exchangeRateBuy: 0,
    exchangeRateSell: 0,
    shippingMethod: '',
    packingMethod: '',
    weightPerContainer: 0,
    estimatedTotalContainers: 0,
    estimatedTotalBookings: 0
  }
};
