export const CODE_EXPORT_PORT = 'EXPORT_PORT';
export const CODE_DESTINATION = 'PORT-DESTINATION';
export const CODE_COUNTRY_IMPORT = 'COUNTRY-IMPORT';
export const CODE_DELIVERY_METHOD = 'DELIVERY-METHOD';
export const CODE_PAYMENT_METHOD = 'PAYMENT_METHOD';
export const CODE_PAYMENT_CURRENCY = 'PAYMENT-CURRENCY';
export const CODE_UNIT_OF_MEASURE = 'UNIT-OF-MEASURE';
export const CODE_PACKING_METHOD = 'PACKING_METHOD';
export const CODE_REGION = 'REGION';
export const CODE_QUALITY_TYPE = 'QUALITY_TYPE';
export const CODE_VEHICLE_TYPE = 'VEHICLE_TYPE';
export const CODE_TRANSPORT_UNIT = 'TRANSPORT_UNIT';
export const CODE_FORWARDER = 'FORWARDER';
export const CODE_SHIPPING_LINE = 'SHIPPING_LINE';

