import { AutoGeneratedField, SearchParams, SimpleResponse, PaginatedResponse } from './common';
import { Status } from '../constants/status';

export type GoodFormData = {
  code: string;
  name: string;
  description: string;
  category: string;
  brand: string;
  model: string;
  sku: string;
  barcode: string;
  unitOfMeasure: string;
  weight: number;
  dimensions: string;
  purchasePrice: number;
  sellingPrice: number;
  minStockLevel: number;
  maxStockLevel: number;
  reorderPoint: number;
  isSellable: number;
  isPurchasable: number;
  taxRate: number;
  supplierId: number;
  originCountry: string;
  expiryDays: number;
  status?: Status;
};

export type Good = AutoGeneratedField & GoodFormData;

// Good response types sử dụng Good entity
export type GoodSimpleResponse = SimpleResponse<Good>;
export type GoodPaginatedResponse = PaginatedResponse<Good>;

export type GoodParams = SearchParams<GoodFormData> & {
  category?: string;
  brand?: string;
  sku?: string;
  unitOfMeasure?: string;
  supplierId?: number;
  originCountry?: string;
  minPrice?: number;
  maxPrice?: number;
};

export type TGood = Good;
