import { AutoGeneratedField, PaginatedResponse, SearchParams, SimpleResponse } from './common';

export type SaleContractFormData = {
    code: string;
    status: number;
    contractId: number;
    contractCode: string | null;
    customerId: number;
    codeBooking: number;
    notes: string | null;
    buyerName: string;
    contractDate: string;
    goodDescription: string;
    paymentTerms: string;
    tolerancePercentage: number | null;
    endUserThermalPower: string | null;
    weightPerContainer: number | null;
    lcNumber: string | null;
    lcDate: string;
    paymentDeadline: string;
    issuingBankId: number;
    advisingBankId: number;
    lcAmount: number;
    currency: string;
    saleContractCode: string;
    lcStatus: string | null;
    saleContractGoods: any[]; // You might want to define a specific type for this array
};

export type SaleContract = AutoGeneratedField & SaleContractFormData;

// For select/dropdown display
export type SaleContractOption = {
    label: string; // code will be displayed
    value: number; // id will be submitted
};

// SaleContract response types
export type SaleContractSimpleResponse = SimpleResponse<SaleContract>;
export type SaleContractPaginatedResponse = PaginatedResponse<SaleContract>;

export type SaleContractParams = SearchParams<SaleContractFormData> & {
    customerId?: number;
    contractId?: number;
    currency?: string;
    paymentTerms?: string;
    status?: number;
};

export type TSaleContract = SaleContract;

// Helper function to convert SaleContract to SelectOption
export const toSaleContractOption = (contract: SaleContract): SaleContractOption => ({
    label: contract.code,
    value: contract.id
});

