import { AutoGeneratedField, SearchParams, SimpleResponse, PaginatedResponse } from './common';
import { Status } from '../constants/status';

export type ShippingLineFormData = {
  description: string;
  code: string;
  name: string;
  status?: Status;
};

export type TShippingLine = AutoGeneratedField & ShippingLineFormData;

// For backward compatibility with existing code
export type ShippingLine = TShippingLine;

// Shipping line response types
export type ShippingLineSimpleResponse = SimpleResponse<TShippingLine>;
export type ShippingLinePaginatedResponse = PaginatedResponse<TShippingLine>;

export type TShippingLineFilter = SearchParams<ShippingLineFormData>;
export type ShippingLineParams = TShippingLineFilter;

export interface TShippingLineResponse {
  data: TShippingLine[];
  meta: {
    message: string;
    total?: number;
    page?: number;
    limit?: number;
  };
}

export interface TShippingLineRequest extends ShippingLineFormData {}

export type TShippingLineStatus = 'active' | 'inactive' | 'all';
