import { AutoGeneratedField, SearchParams, SimpleResponse, PaginatedResponse } from './common';
import { Status } from '../constants/status';

export type StockFormData = {
  contractId: number;
  goodId: number;
  goodName: string;
  userId: number;
  userName : string;
  contractType : string;
  transactionType: string;
  quantity: number;
  transactionDate :string;
  note: string;
  status?: Status;
};


export type Stock = AutoGeneratedField & StockFormData;

// Stock response types sử dụng Stock entity
export type StockSimpleResponse = SimpleResponse<Stock>;
export type StockPaginatedResponse = PaginatedResponse<Stock>;

export type StockParams = SearchParams<StockFormData> & {
  
};

export type TStock = Stock;